#include <iostream.h>
 main ()
{ int Bil1,Bil2;

cout<<" Masukan Bilangan Pertama : ";
cin>>Bil1;
cout<<" Masukan Bilangan Kedua : ";
cin>>Bil2;
cout<<"Hasil "<<Bil1<<" + "<<Bil2<<" ="<<(Bil1+Bil2);
cout<<"Hasil "<<Bil1<<" - "<<Bil2<<" ="<<(Bil1-Bil2);
cout<<"Hasil "<<Bil1<<" * "<<Bil2<<" ="<<(Bil1*Bil2);
cout<<"Hasil "<<Bil1<<" / "<<Bil2<<" ="<<(Bil1/Bil2);
cout<<"Hasil "<<Bil1<<" % "<<Bil2<<" ="<<(Bil1%Bil2);
return (0);
}

